#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=00:00:10
#PBS -q batch
#PBS -N COMP3450_LA1
#PBS -j oe

#cat $PBS_NODEFILE
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ~/assignments/LA1/mvp-student.cx
