#!/bin/bash
#PBS -l nodes=8:ppn=12
#PBS -l walltime=00:15:00
#PBS -q batch
#PBS -N send_receive_int
#PBS -j oe

#cat $PBS_NODEFILE
cd ~/DIR/PROG/
echo "Token ring:"
mpiexec -np 8 --map-by ppr:1:node --hostfile $PBS_NODEFILE ~/assignments/PA1/tokenring.cx
echo "Token ring big:"
mpiexec -np 8 --map-by ppr:1:node --hostfile $PBS_NODEFILE ~/assignments/PA1/tokenringbig.cx
echo "Tree big:"
mpiexec -np 8 --map-by ppr:1:node --hostfile $PBS_NODEFILE ~/assignments/PA1/treebig.cx
