#!/bin/bash
#PBS -l nodes=10:ppn=12,walltime=00:15:00
#PBS -q batch
#PBS -N LA5_output
#PBS -j oe
#this should work to send the env, but it's not
#PBS -V

#cat $PBS_NODEFILE
cd /home/rivnakm/assignments/LA5
for nodes in 1 2 4 6 8 10 
do
    mpiexec -np $nodes --map-by ppr:2:node --hostfile $PBS_NODEFILE /home/rivnakm/assignments/LA5/LA5.cx
done
