#!/bin/bash
#PBS -l nodes=10:ppn=12,walltime=00:07:00
#PBS -q batch
#PBS -N LA4_Convolve
#PBS -j oe
#this should work to send the env, but it's not
#PBS -V

#cat $PBS_NODEFILE
cd /home/rivnakm/assignments/LA3
mpiexec -np 10 --map-by ppr:2:node --hostfile $PBS_NODEFILE /home/rivnakm/assignments/LA4/LA4parallel.cx
